@echo off
setlocal

cd /d "%~dp0"

set "OGRE_SOURCE_DIR=%CD%"
set "OGRE_BUILD_DIR=%~dp0..\Build\OgreNextVS2022"

if not exist "%OGRE_BUILD_DIR%" (
    mkdir "%OGRE_BUILD_DIR%"
)

cmake --fresh ^
    -S "%OGRE_SOURCE_DIR%" ^
    -B "%OGRE_BUILD_DIR%" ^
    -G "Visual Studio 17 2022" ^
    -A x64 ^
    -DOGRE_CONFIG_ENABLE_FREEIMAGE=OFF ^
    -DOGRE_CONFIG_ENABLE_ZIP=OFF ^
    -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=OFF ^
    -DOGRE_BUILD_RENDERSYSTEM_VULKAN=OFF ^
    -DOGRE_BUILD_SAMPLES2=OFF ^
    -DOGRE_BUILD_TOOLS=OFF ^
    -DOGRE_BUILD_PLUGIN_PFX=OFF ^
    -DOGRE_BUILD_PLUGIN_PFX2=OFF ^
    -DOGRE_INSTALL_SAMPLES=OFF ^
    -DOGRE_INSTALL_TOOLS=OFF ^
    -DOGRE_INSTALL_DOCS=OFF

endlocal